AWSTemplateFormatVersion: '2010-09-09'
Description: 'Data Lake Infrastructure for Data Processing Pipeline'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name

  ProjectName:
    Type: String
    Default: data-pipeline
    Description: Project name

Resources:
  # S3 Buckets
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${ProjectName}-raw-data
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToStandardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  ProcessedDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${ProjectName}-processed-data
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToStandardIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  AnalyticsDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-${ProjectName}-analytics-data
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub ${EnvironmentName}_${ProjectName}_db
        Description: !Sub Database for ${ProjectName} in ${EnvironmentName} environment

  # Glue Crawlers
  RawDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub ${EnvironmentName}-${ProjectName}-raw-data-crawler
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${RawDataBucket}/
      Schedule:
        ScheduleExpression: cron(0 0 * * ? *)
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"},"Tables":{"AddOrUpdateBehavior":"MergeNewColumns"}}}'
      Tags:
        Environment: !Ref EnvironmentName
        Project: !Ref ProjectName

  ProcessedDataCrawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub ${EnvironmentName}-${ProjectName}-processed-data-crawler
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub s3://${ProcessedDataBucket}/
      Schedule:
        ScheduleExpression: cron(0 0 * * ? *)
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG
      Configuration: '{"Version":1.0,"CrawlerOutput":{"Partitions":{"AddOrUpdateBehavior":"InheritFromTable"},"Tables":{"AddOrUpdateBehavior":"MergeNewColumns"}}}'
      Tags:
        Environment: !Ref EnvironmentName
        Project: !Ref ProjectName

  # IAM Role for Glue
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${RawDataBucket}
                  - !Sub arn:aws:s3:::${RawDataBucket}/*
                  - !Sub arn:aws:s3:::${ProcessedDataBucket}
                  - !Sub arn:aws:s3:::${ProcessedDataBucket}/*
                  - !Sub arn:aws:s3:::${AnalyticsDataBucket}
                  - !Sub arn:aws:s3:::${AnalyticsDataBucket}/*

  # CloudWatch Logs
  GlueLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/glue/${EnvironmentName}-${ProjectName}
      RetentionInDays: 30

Outputs:
  RawDataBucketName:
    Description: Name of the raw data bucket
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub ${EnvironmentName}-${ProjectName}-RawDataBucket

  ProcessedDataBucketName:
    Description: Name of the processed data bucket
    Value: !Ref ProcessedDataBucket
    Export:
      Name: !Sub ${EnvironmentName}-${ProjectName}-ProcessedDataBucket

  AnalyticsDataBucketName:
    Description: Name of the analytics data bucket
    Value: !Ref AnalyticsDataBucket
    Export:
      Name: !Sub ${EnvironmentName}-${ProjectName}-AnalyticsDataBucket

  GlueDatabaseName:
    Description: Name of the Glue database
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub ${EnvironmentName}-${ProjectName}-GlueDatabase

  GlueServiceRoleArn:
    Description: ARN of the Glue service role
    Value: !GetAtt GlueServiceRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-${ProjectName}-GlueServiceRoleArn

